before_script:
  - sudo apt-add-repository ppa:swi-prolog/stable -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox
  - swipl -g 'pack_install(julian, [interactive(false)]),halt.'
  - swipl -g 'pack_install(tap, [interactive(false)]),halt.'

script: make tests